{
  "is_firewall_open" : false,
  "billboard_bg_url" : "https:\/\/dl.cdn.freefiremobile.com\/common\/OB23\/version\/Patch_Bg.png",
  "gop_url" : "",
  "gamevar" : "var_name,comment,var_type,var_value,var_region,var_platform\nvar_name,comment,var_type,var_value,var_region,var_platform\nFastQuit_NativeDoneFast,FastQuit_NativeDoneFast,bool,true,,\nProcessModelInitAfterLoginInDeserialize,ProcessModelInitAfterLoginInDeserialize,bool,false,,\nEnableRecylePlayer,EnableRecylePlayer,bool,false,,\nEnableSlicedDestroyStremaerObject,EnableSlicedDestroyStremaerObject,bool,false,,\n",
  "core_url" : "csoversea.castle.freefiremobile.com",
  "login_download_optionalpack" : "optionalclothres:shaders|optionalpetres:optionalpetres_commonab_shader|optionallobbyres:",
  "need_check_ip_list" : [
    "202.81.108.9"
  ],
  "web_log_server" : "https:\/\/networkselftest.ff.garena.com\/api\/",
  "remote_version" : "1.109.12",
  "force_refresh_restype" : "optionalavatarres",
  "max_video" : "",
  "max_store" : "",
  "garena_hint" : false,
  "billboard_cdn_url" : "https:\/\/dl.dir.freefiremobile.com\/common\/OB48\/CSH\/patchupdate\/naenFjei38HE9bR01.ff_extend;https:\/\/dl.dir.freefiremobile.com\/common\/OB48\/CSH\/patchupdate\/naenFjei38HE9bR02.ff_extend;https:\/\/dl.dir.freefiremobile.com\/common\/OB48\/CSH\/patchupdate\/naenFjei38HE9bR03.ff_extend;https:\/\/dl.dir.freefiremobile.com\/common\/OB48\/CSH\/patchupdate\/naenFjei38HE9bR04.ff_extend;https:\/\/dl.dir.freefiremobile.com\/common\/OB48\/CSH\/patchupdate\/naenFjei38HE9bR05.ff_extend;https:\/\/dl.dir.freefiremobile.com\/common\/OB48\/CSH\/patchupdate\/naenFjei38HE9bR06.ff_extend",
  "test_url" : "",
  "client_ip" : "174.171.23.12",
  "need_track_hotupdate" : true,
  "max_web" : "",
  "use_background_download" : false,
  "cdn_url" : "https:\/\/dl.gmc.freefiremobile.com\/live\/ABHotUpdates\/",
  "use_login_optional_download" : true,
  "use_background_download_lobby" : false,
  "login_failed_count" : 0,
  "code" : 0,
  "network_log_server" : "https:\/\/na.network.freefiremobile.com\/",
  "appstore_url" : "https:\/\/itunes.apple.com\/app\/id1300146617",
  "patchnote_url" : "https:\/\/dl.dir.freefiremobile.com\/common\/web_event\/aswqooiwd\/CK4GyNYn.html?lang=en",
  "remote_option_version" : "optionallocres:0|optionalavatarres:537|optionalclothres:199999|optionalfootballres:27|optionalfullscreencgres:305|optionalhuntinggroundres:245|optionalinfection:125|optionalingameres:330|optionallobbyres:399|optionallonewolfres:71|optionallonewolfstrikeoutres:59|optionalludores:42|optionalmap1res:314|optionalmap2res:156|optionalmap4res:139|optionalmaphippores:115|optionalmapres:357|optionalnewblast:163|optionalpetres:686|optionalrushb:108|optionalrushingpetsres:84|optionalsnowduelres:35|optionalsocialres:166|optionaltrainingres:234|optionalugcres:624|optionalvoiceres:317|optionalwerewolves:153",
  "garena_login" : false,
  "latest_release_version" : "OB48",
  "use_multithread_hash" : false,
  "country_code" : "US",
  "core_ip_list" : [
    "0.0.0.0",
    "50.109.27.134",
    "129.226.2.163",
    "129.226.1.13",
    "129.226.1.16"
  ],
  "min_hint_size" : 1,
  "is_review_server" : false,
  "backup_cdn_url" : "https:\/\/dl.gmc.freefiremobile.com\/live\/ABHotUpdates\/",
  "img_cdn_url" : "https:\/\/dl.gmc.freefiremobile.com\/common\/",
  "is_server_open" : true,
  "server_url" : "https:\/\/loginbp.ggblueshark.com\/",
  "billboard_msg" : "",
  "web_url" : "",
  "gdpr_version" : 0
}
